spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=eureka-test
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8761
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/eureka-test/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=RewritePath=/eureka-test/(?<segment>.*), /${segment}